### ISSUE TITLE
webhook URL is not recognized and/or the plugin is not sending information to the discord channel

### ISSUE THREAD

**Issue by LaFesta1749** [GraczBezNicku/PlaytimeCounter#1]
@GraczBezNicku: The webhook URL is not recognized and/or the plugin is not sending information to the discord channel.
Can you please check if it's a problem related to the plugin or if it's related to me being a dum dum? Thanks ♥

Using RA - ct:
![image](https://github.com/GraczBezNicku/PlaytimeCounter/assets/1494298/629ed23f-eb14-4b5e-9588-3cf49ef43061)

Discord channel is empty:
![image](https://github.com/GraczBezNicku/PlaytimeCounter/assets/1494298/7b28dda6-04f5-457a-8023-c8a41d0e3c70)

Plugin config:
```
is_enabled: true
debug_mode: true
# List of groups to log playtime of.
groups_to_log:
- owner
- senior_admin
- admin
- junior_admin
- moderator
# List of groups and their playtime requirement in seconds. If met, reqResult will change based on your config.
group_reqs:
  owner: 28800
  senior_admin: 28800
  admin: 28800
  junior_admin: 28800
  moderator: 28800
webhook_u_r_l: https://discord.com/api/webhooks/1108295618054606949/xW_Ed7Onc69ihGopP21gIy3X8OmLiFFHmL7IjPd82-LYesBclfCodPWUUp2R-09BgbFA
webhook_avatar_u_r_l: https://cdn.discordapp.com/attachments/434037173281488899/940610688760545290/mrozonyhyperthink.jpg
discord_webhook_cooldown: 10
summary_check_cooldown: 300
# First line when printing playtime summary
webhook_count_message: >
  Playtime summary: 
# Lines printed out for users which have playtime recorded. Accepts parameters: {steamID64}, {nickname}, {group}, {hours}, {minutes}, {seconds}, {reqResult}
webhook_count_user_message: >
  **{nickname} ({steamID64}) [{group}]** has played for **{minutes}m ({seconds}s)** - {reqResult} 
webhook_req_result_met: ':white_check_mark:'
webhook_req_result_not_met: ':x:'
webhook_req_result_unknown: ':warning:'
# Message that will display on discord. (can use {seconds} and {hours} too)
webhook_message: '{time} **{player}** left the server after playing for **{minutes}** minutes'
```

Discord webhook created for the specified channel:
![image](https://github.com/GraczBezNicku/PlaytimeCounter/assets/1494298/5bcae79d-b3d7-4caa-846f-e762b1409c10)
